name: iOS Tweak Build V4
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: theos/setup-theos@v1 # Tayyor Theos o'rnatuvchi Action

      - name: Setup SDKs
        run: |
          # SDK-ni boshqa ishonchli manbadan yuklash
          svn checkout https://github.com/theos/sdks/trunk/iPhoneOS16.5.sdk $THEOS/sdks/iPhoneOS16.5.sdk

      - name: Build Dylib
        run: |
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SubwayMod-Dylib
          path: .theos/obj/debug/*.dylib
